name: CPython Build

on:
  workflow_dispatch:
    inputs:
      cpython_branch:
        description: 'CPython branch to clone'
        required: true
        default: 'v3.13.1'
        type: text
      optimize_level:
        description: 'wasm-opt optimize level'
        required: true
        default: '4'
        type: text

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: CPython Build in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/Avril112113/build-cpython-wasi
          cacheFrom: ghcr.io/Avril112113/build-cpython-wasi
          push: always
          env: |
            CPYTHON_BRANCH=${{ cpython_branch }}
            OPTIMIZE_LEVEL=${{ optimize_level }}
          runCmd: ./build-wasi.sh
